controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints: [joint_1, joint_l_2, joint_l_3, joint_l_4, joint_l_5, joint_l_6, joint_l_7,
               joint_r_2, joint_r_3, joint_r_4, joint_r_5, joint_r_6, joint_r_7]
      state_interfaces: [position, velocity]

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints: [joint_1, joint_l_2, joint_l_3, joint_l_4, joint_l_5, joint_l_6, joint_l_7,
               joint_r_2, joint_r_3, joint_r_4, joint_r_5, joint_r_6, joint_r_7]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      constraints:
        stopped_velocity_tolerance: 0.01
      open_loop_control: true
